<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help()
 * works by telling Drupal if a user is looking at the route we specified (help.page.hello_world in this example),
 * show the info contained in the $output variable.
 */
function hello_world_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hello_world':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is an example module.') . '</p>';
      return $output;

    default:
  }
}
